#!/bin/bash

#variaveis
corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"



SHELL=/bin/sh
PATH=/sbin:/usr/sbin:/usr/bin:/bin

if [ -e "/root/scripts/" ]
then
#echo " o diretorio existe"
echo -e " \033[0;32m  o diretorio existe  \033[0m             --> 0;32 "
else
echo -e " \033[1;31m o diretorio não existe vamos criar o diretorio  \033[0m    --> 1;31 "
#echo " o diretorio não existe vamos criar o diretorio"
mkdir /root/scripts/
fi
exit
